file:
    path:
      fhv: tripdata/fhv_tripdata_2018-01.csv
      green: tripdata/green_tripdata_2018-01.csv
      yellow: tripdata/yellow_tripdata_2018-01.csv

spring:
   datasource: 
      driverClassName: org.h2.Driver
      url: "jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=TRUE;FILE_LOCK=NO"
      username: "sa"
      password: ""
      initialization-mode: always
      
   jpa:    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: none
    
   h2:    console:       path: /console/       enabled: true
       
server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false